apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cve
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-cve
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-cve/releases/download/{{ .TagName }}/kubectl-cve_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-cve
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-cve/releases/download/{{ .TagName }}/kubectl-cve_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-cve
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-cve/releases/download/{{ .TagName }}/kubectl-cve_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-cve
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-cve/releases/download/{{ .TagName }}/kubectl-cve_{{ .TagName }}_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-cve
  shortDescription: Show the subject that's currently authenticated as.
  description: |
    This plugin show the subject that's currently authenticated as.

